name: GitHub Actions Practica
on: [push]

jobs:
  explorando:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar evento
        run: echo "Evento: ${{ github.event_name }}"

      - name: Mostrar sistema operativo del runner
        run: echo "Runner: ${{ runner.os }}"

      - name: Listar archivos del repositorio
        run: ls ${{ github.workspace }}
